title: 我和Hit FM的故事
google_analytics: UA-10976235-10
layout: default
story_full: true

collections:
  extras:
    output: true
    permalink: /extra/:name
  topics:
    output: true
    permalink: /topic/:name
  stories:
    output: true
    permalink: /story/:name
